---
- name: Push aci_model

  # We prepare an aci_login anchor for convenience
  vars:
    aci_login: &aci_login
      hostname: '{{ inventory_hostname }}'
      username: '{{ username }}'
      password: '{{ password }}'
      use_proxy: '{{ apic_use_proxy }}'
      validate_certs: '{{ apic_validate_certs }}'

  # We define the delegate_to at the block-level
  delegate_to: localhost

  block:
    - name: Create tenants
      aci_tenant:
        <<: *aci_login
        tenant: '{{ item.tenant_name }}'
        description: '{{ item.tenant_description }}'
      with_items: '{{ aci_model_data|aci_listify("tenant") }}'

    - name: Add VLAN pools
      aci_vlan_pool:
        <<: *aci_login
        pool: '{{item.access_policy_vlan_pool_name}}'
        pool_allocation_mode: '{{item.access_policy_vlan_pool_alloc}}'
        description: Configured by Ansible
        state: '{{state}}'
      with_items: '{{ aci_model_data|aci_listify("access_policy","vlan_pool") }}'

    - name: Add a new VLAN encap block
      aci_vlan_pool_encap_block:
        <<: *aci_login
        block_name: "{{global.vlan_pool}}"
        pool: "{{global.vlan_pool}}"
        pool_allocation_mode: static
        block_start: "{{global.vlan_min}}"
        block_end: "{{global.vlan_max}}"
        state: "{{state}}"
      with_items: '{{ aci_model_data|aci_listify("access_policy","vlan_pool","encap_block") }}'
