---
- name: Push aci_model

  # We prepare an aci_login anchor for convenience
  vars:
    aci_login: &aci_login
      hostname: '{{ inventory_hostname }}'
      username: '{{ username }}'
      password: '{{ password }}'
      use_proxy: '{{ apic_use_proxy }}'
      validate_certs: '{{ apic_validate_certs }}'

  # We define the delegate_to at the block-level
  delegate_to: localhost

  block:
    - name: Create tenants
      aci_tenant:
        <<: *aci_login
        tenant: '{{ item.tenant_name }}'
        description: '{{ item.tenant_description }}'
      with_items: '{{ aci_model_data|aci_listify("tenant") }}'

    - name: Add VLAN pools
      aci_vlan_pool:
        <<: *aci_login
        pool: '{{item.access_policy_vlan_pool_name}}'
        pool_allocation_mode: '{{item.access_policy_vlan_pool_alloc}}'
        description: Configured by Ansible
        state: '{{state}}'
      with_items: '{{ aci_model_data|aci_listify("access_policy","vlan_pool") }}'

    - name: Add a new VLAN encap block
      aci_vlan_pool_encap_block:
        <<: *aci_login
        block_name: "{{item.access_policy_vlan_pool_name}}"
        pool: "{{item.access_policy_vlan_pool_name}}"
        pool_allocation_mode: '{{item.access_policy_vlan_pool_alloc}}'
        block_start: "{{item.access_policy_vlan_pool_encap_block_from}}"
        block_end: "{{item.access_policy_vlan_pool_encap_block_to}}"
        state: "{{state}}"
      with_items: '{{ aci_model_data|aci_listify("access_policy","vlan_pool","encap_block") }}'

    - name: Add physical domains
      aci_domain:
        <<: *aci_login
        domain: "{{item.access_policy_physical_domain_name}}"
        domain_type: phys
        state: "{{state}}"
      with_items: '{{ aci_model_data|aci_listify("access_policy","physical_domain") }}'

    - name: Add a new AEP
      aci_aep:
        <<: *aci_login
        aep: "{{item.access_policy_aep_name}}"
        description: Configured by ansible
        state: "{{state}}"
      with_items: '{{ aci_model_data|aci_listify("access_policy","aep") }}'

    - name: Link AEPs to domains
      aci_aep_to_domain: #&binding_present
        <<: *aci_login
        aep: "{{item.access_policy_aep_name}}"
        domain: "{{item.access_policy_aep_domain_name}}"
        domain_type: phys
        state: "{{state}}"
      with_items: '{{ aci_model_data|aci_listify("access_policy","aep", "domain") }}'

    - name: Bind a physical domain to VLAN pool
      aci_domain_to_vlan_pool:
        <<: *aci_login
        domain: "{{item.access_policy_physical_domain_name}}"
        domain_type: '{{item.access_policy_physical_domain_vlan_pool_alloc}}'
        pool: "{{item.access_policy_physical_domain_vlan_pool}}"
        pool_allocation_mode: static
        state: "{{state}}"
      with_items: '{{ aci_model_data|aci_listify("access_policy","physical_domain") }}'

    - name: creating a Leaf Profile with description
      aci_switch_policy_leaf_profile:
        <<: *aci_login
        leaf_profile: "{{item.access_policy_switch_policy_profile_name}}"
        description: Configured by ansible
        state: "{{state}}"
      with_items: '{{ aci_model_data|aci_listify("access_policy","switch_policy_profile") }}'

    - name: adding a switch policy leaf profile selector associated Node Block range (w/ policy group)
      aci_switch_leaf_selector:
        <<: *aci_login
        leaf_profile: "{{item.access_policy_switch_policy_profile_name}}"
        leaf: "{{item.access_policy_switch_policy_profile_leaf_selector_name}}"
        leaf_node_blk: "{{item.access_policy_switch_policy_profile_leaf_selector_name}}"
        from: "{{item.access_policy_switch_policy_profile_leaf_selector_from}}"
        to: "{{item.access_policy_switch_policy_profile_leaf_selector_to}}"
        state: "{{state}}"
      with_items: '{{ aci_model_data|aci_listify("access_policy","switch_policy_profile","leaf_selector") }}'

