---
- name: Push aci_model

  # We prepare an aci_login anchor for convenience
  vars:
    aci_login: &aci_login
      hostname: '{{ inventory_hostname }}'
      username: '{{ username }}'
      password: '{{ password }}'
      use_proxy: '{{ apic_use_proxy }}'
      validate_certs: '{{ apic_validate_certs }}'

  # We define the delegate_to at the block-level
  delegate_to: localhost

  block:
    - name: Create tenants
      aci_tenant:
        <<: *aci_login
        tenant: '{{ item.tenant_name }}'
        description: '{{ item.tenant_description }}'
      with_items: '{{ aci_model_data|aci_listify("tenant") }}'

    - name: Add VLAN pools
      aci_vlan_pool:
        <<: *aci_login
        path: /api/node/mo/uni/infra/vlanns-[{{ item.access_policy_vlan_pool_name }}]-{{ item.access_policy_vlan_pool_alloc }}.json
        method: post
        content:
          {"fvnsVlanInstP":{"attributes":{"allocMode":"{{ item.access_policy_vlan_pool_alloc }}","descr":"","dn":"uni/infra/vlanns-[{{ item.access_policy_vlan_pool_name }}]-{{ item.access_policy_vlan_pool_alloc }}","name":"{{ item.access_policy_vlan_pool_name }}","ownerKey":"","ownerTag":""}}}
      with_items: '{{ aci_model_data|aci_listify("access_policy","vlan_pool") }}'
