---
#- name: Debug
#  with_items: '{{ aci_model_data|aci_listify("access_policy","switch_policy_profile","leaf_selector") }}'
#  debug:
#   # loop: "{{item.interfaces}}"
#    msg: "{{item}}"


- name: Debug
  with_items: '{{ aci_model_data|aci_listify("access_policy","interface_policy","interface_selector") }}'
  debug:
   # loop: "{{item.access_policy_interface_policy_profile_name}}"
    msg: "{{item}}"
