---
- name: Debug
  with_items: '{{ aci_topology|aci_listify("access_policy","switch_policy_profile","leaf_selector") }}'
#  with_items: '{{vars.aci_topology}}'
  debug:
   # loop: "{{item.interfaces}}"
    msg: "{{item}}"

